package craft;

public enum BlockedReason {
    NONE,
    NO_RECIPE,
    PRICE_UNAVAILABLE,
    BUYING_DISABLED,
    DAILY_LIMIT,
    CYCLE_DETECTED,
    RECIPE_NOT_ALLOWED,
    INSUFFICIENT_BUDGET
}
